// Biblioteca de títulos y bajadas por tipo de email — voz Ligier (curador, sin superlativos ni exclamaciones)

export const TITULOS = {
  vinos: [
    "Esta semana,\nelegimos seis.",
    "Difícil\nquedarse\ncon uno solo.",
    "Seis etiquetas\nque conocemos\nde memoria.",
    "Los que\nguardamos\npara vos.",
    "Una selección\nque vale\ncada peso.",
    "Mendoza\nen seis\ncopas.",
    "Del viñedo\na tu mesa\nesta semana.",
    "Seis razones\npara abrir\nuna botella.",
    "Lo mejor\ndel mes\nen seis etiquetas.",
    "Elegimos.\nVos decidís\ncuántas llevás.",
    "Tintos que\ndicen algo\ndistinto.",
    "La selección\nque no\nfalla.",
    "Seis vinos,\nuna misma\nidea.",
    "Lo que\nestamos\ntomando ahora.",
    "Etiquetas\nque pasan\nla prueba.",
    "Para la mesa\nde esta\nsemana.",
    "Seis que\nvalen la\npena abrir.",
    "Nuestra\nselección\nde la semana.",
    "Vinos con\nnombre\npropio.",
    "Lo que\nrecomendamos\nhoy.",
  ],
  whisky: [
    "Destilados\nque cuentan\nsu historia.",
    "Single malts\ny blends\nde carácter.",
    "Esta semana,\nelegimos\nlo mejor.",
    "Escocia,\nIrlanda,\ny más allá.",
    "Años de\nañejamiento\nen cada sorbo.",
    "Para los que\nsaben lo que\nquieren.",
    "Un dram\nque vale\ncada peso.",
    "La cava\nde whisky\nde Ligier.",
    "Maltas que\npiden\ntiempo.",
    "Lo que\nguardamos\npara el final.",
    "Destilados\ncon\nprocedencia.",
    "El whisky\nque elegimos\neste mes.",
    "Carácter\nen cada\nbotella.",
    "Para tomar\nsin\napuro.",
    "Una selección\npara\nconocedores.",
  ],
  espirituosas: [
    "Para armar\ntu barra\nen serio.",
    "Alta graduación,\ncarácter\npropio.",
    "El trago\nperfecto\nempieza acá.",
    "Destilados\nde autor\npara tu mesa.",
    "Para los que\nno se\nconforman.",
    "La barra\nque siempre\nquisiste.",
    "Gin, ron,\nvodka\ny más.",
    "Lo que\nfalta en\ntu barra.",
    "Cócteles\nque empiezan\nacá.",
    "Botellas\ncon\npersonalidad.",
    "Para mezclar\no tomar\nsolo.",
    "El espíritu\nde la\nnoche.",
    "Destilados\nque valen\nla pena.",
    "Armá tu\nbarra con\ncriterio.",
    "Lo mejor\npara\ncoctelería.",
  ],
  "vinos-guardados": [
    "Algunos vinos\nno vuelven.",
    "El tiempo\nhizo el trabajo.",
    "Botellas que\nya no se repiten.",
    "Lo que el\ntiempo construyó.",
    "Vinos de\notra época.",
    "La rareza\ntiene nombre.",
    "Lo que nadie\nmás tiene.",
    "Una cava\nque habla sola.",
    "Guardados\npor años.",
    "El paso\ndel tiempo.",
    "Cosechas que\nno se consiguen.",
    "Lo que queda\nde esos años.",
    "Botellas\nirrepetibles.",
    "Memoria\nen una copa.",
    "Tiempo\nembotellado.",
  ],
  "wine-club": [
    "Cada mes,\nvinos que\nno encontrás.",
    "Una membresía\nque sabe\nlo que hacés.",
    "El club\nque curó\nla cava.",
    "Acceso a\nlo que aún\nno salió.",
    "Ligier\nselecciona.\nVos disfrutás.",
    "Vinos\nelegidos\npara vos.",
    "Pertenecé\nal\nclub.",
    "Una cava\nque crece\ncada mes.",
    "Más que\nvino:\ncriterio.",
    "El club\nde los que\nsaben.",
  ],
  experiencias: [
    "Una noche\nque no\nse olvida.",
    "La cena\nque siempre\nquisiste.",
    "Ligier\nte invita\na la mesa.",
    "Una experiencia\ncurada\npara vos.",
    "Comer bien\nes un\narte.",
    "Una mesa,\nuna\nhistoria.",
    "Maridajes\nque\nsorprenden.",
    "La velada\nperfecta\nempieza acá.",
    "Vino,\nmesa\ny compañía.",
    "Una noche\ncon\nnombre propio.",
  ],
  "gift-cards": [
    "El regalo\nque siempre\nacertás.",
    "Para el que\ntiene buen\npaladar.",
    "Un regalo\ncon\ncriterio.",
    "Dale lo\nque realmente\nquiere.",
    "La elección\nqueda en\nsus manos.",
    "Regalá\nbuen\ngusto.",
    "Para quien\nsabe\nelegir.",
    "Un detalle\nque se\nnota.",
    "El gusto\nde\nelegir.",
    "Regalá\nuna buena\nbotella.",
  ],
};

export const BAJADAS = {
  vinos: [
    "Una selección para descubrir esta semana.<br>Llevá 6, pagá 5.",
    "Tintos, blancos y rosados elegidos uno por uno.<br>Llevá 6, pagá 5.",
    "Etiquetas de Mendoza y más allá.<br>Llevá 6, pagá 5.",
    "Lo que estamos recomendando ahora.<br>Podés mezclar etiquetas.",
    "De Altamira a Gualtallary, lo mejor del mes.<br>Llevá 6, pagá 5.",
    "Vinos para abrir hoy o guardar un tiempo.<br>Llevá 6, pagá 5.",
    "Una vuelta por nuestras etiquetas favoritas.<br>Podés mezclar las que quieras.",
    "Seleccionados para acompañar tu mesa.<br>Llevá 6, pagá 5.",
    "Cada botella, una decisión que tomamos por vos.<br>Llevá 6, pagá 5.",
    "Lo que vale la pena descorchar esta semana.<br>Podés combinar etiquetas.",
    "Clásicos y descubrimientos, todo junto.<br>Llevá 6, pagá 5.",
    "Vinos con carácter, elegidos con criterio.<br>Llevá 6, pagá 5.",
    "Una selección honesta, sin vueltas.<br>Llevá 6, pagá 5.",
    "Para los que disfrutan cada copa.<br>Podés mezclar etiquetas.",
    "Lo mejor de nuestra cava, esta semana.<br>Llevá 6, pagá 5.",
  ],
  whisky: [
    "Single malts y blends elegidos uno por uno.",
    "Destilados con procedencia y carácter.",
    "De Escocia a Japón, lo que vale la pena.",
    "Años de añejamiento en cada botella.",
    "Para tomar sin apuro, como se debe.",
    "Una selección para conocedores.",
    "Maltas que piden tiempo y buena compañía.",
    "Lo que guardamos para las ocasiones.",
    "Carácter, madera y tiempo en cada sorbo.",
    "Destilados que cuentan de dónde vienen.",
    "Para los que saben lo que buscan.",
    "Botellas que valen cada peso.",
    "Lo mejor de nuestra cava de whisky.",
    "Procedencia y carácter, sin concesiones.",
    "Una vuelta por las maltas que elegimos.",
  ],
  espirituosas: [
    "Todo lo que falta para armar tu barra.",
    "Gin, ron, vodka y destilados de autor.",
    "Para mezclar o tomar solo, vos elegís.",
    "Botellas con personalidad para tu barra.",
    "El punto de partida de cualquier cóctel.",
    "Destilados elegidos para coctelería.",
    "Armá tu barra con criterio.",
    "Lo que necesitás para los tragos de la casa.",
    "Alta graduación y carácter propio.",
    "Para los que disfrutan preparar un buen trago.",
    "Una selección para la barra de tu casa.",
    "Espíritus que hacen la diferencia.",
    "De la barra clásica a la de autor.",
    "Todo para que armes tu propia carta.",
    "Lo mejor para mezclar en casa.",
  ],
  "vinos-guardados": [
    "Botellas que el tiempo hizo únicas.",
    "Cosechas que ya no se consiguen.",
    "Vinos guardados por años, para este momento.",
    "Lo que el paso del tiempo volvió irrepetible.",
    "Etiquetas que no vuelven a estar.",
    "Una cava construida con paciencia.",
    "Vinos de otra época, intactos.",
    "Lo que quedó de esas añadas.",
    "Botellas con historia y procedencia.",
    "Rarezas que el tiempo hizo posibles.",
    "Para quienes valoran lo que no se repite.",
    "Cada botella, un momento que ya pasó.",
    "Lo que guardamos cuando todavía se conseguía.",
    "Memoria líquida de grandes cosechas.",
    "Vinos que el tiempo terminó de hacer.",
  ],
  "wine-club": [
    "Cada mes, una selección que no vas a encontrar.",
    "Acceso preferencial a nuestra cava.",
    "Vinos elegidos por nosotros, para vos.",
    "Una membresía pensada para los que saben.",
    "Más que vino: criterio cada mes.",
    "Pertenecé a la comunidad de Ligier.",
    "Lo que aún no salió a la venta, primero para vos.",
    "Una cava que crece todos los meses.",
    "El club de los que disfrutan descubrir.",
    "Vinos curados, entregados en tu puerta.",
  ],
  experiencias: [
    "Una velada curada por Ligier.",
    "Maridajes pensados para sorprender.",
    "Vino, mesa y buena compañía.",
    "Una noche con nombre propio.",
    "La experiencia de comer y beber bien.",
    "Cenas que se recuerdan.",
    "Una mesa, una historia para contar.",
    "Para vivir el vino de otra manera.",
    "Encuentros alrededor de una buena botella.",
    "La velada perfecta, curada al detalle.",
  ],
  "gift-cards": [
    "El regalo para quien sabe elegir.",
    "Dale la libertad de elegir su botella.",
    "Un regalo con criterio y buen gusto.",
    "Para el que valora una buena copa.",
    "La elección queda en sus manos.",
    "Regalá buen gusto, sin equivocarte.",
    "Un detalle que se nota.",
    "Para quien disfruta del buen vino.",
    "El gusto de elegir, de regalo.",
    "Una buena botella, a su elección.",
  ],
};

// Líneas de asunto por tipo — el subject INFORMA, no vende. Sin superlativos, sin
// exclamaciones, sin ¡/¿. La promo NO va en el subject principal (va en el preheader).
// Longitud objetivo: 28–42 caracteres.
export const SUBJECTS = {
  vinos: [
    "Seis tintos para esta semana",
    "Malbecs de Altamira y Gualtallary",
    "La selección de vinos de la semana",
    "Seis etiquetas elegidas a mano",
    "Lo que estamos recomendando hoy",
  ],
  whisky: [
    "Single malts de Escocia y Japón",
    "Whisky para tomar sin apuro",
    "Destilados con procedencia",
    "La cava de whisky de Ligier",
  ],
  espirituosas: [
    "Para armar tu barra en serio",
    "Lo que le falta a tu barra",
    "Destilados de autor para tu mesa",
    "Gin, ron y destilados elegidos",
  ],
  "vinos-guardados": [
    "Cosechas que ya no se consiguen",
    "Vinos guardados por años",
    "Botellas que el tiempo hizo únicas",
    "La cava guardada de Ligier",
  ],
  "wine-club": [
    "El club que curó la cava",
    "Vinos elegidos para vos, cada mes",
    "Acceso a lo que aún no salió",
  ],
  experiencias: [
    "Una velada curada por Ligier",
    "Maridajes, fecha y lugar",
    "Una noche alrededor del vino",
  ],
  "gift-cards": [
    "El regalo para quien sabe elegir",
    "Una buena botella, a su elección",
    "Un regalo con criterio",
  ],
};

// Preheader (texto de preview en la bandeja) — COMPLEMENTA el subject, no lo repite.
// Acá sí puede ir la promo. Longitud objetivo: 40–90 caracteres.
export const PREHEADERS = {
  vinos: [
    "Elegimos uno por uno. Llevá 6, pagá 5.",
    "Nuestra selección de la semana. Podés mezclar etiquetas.",
    "Seis que conocemos de memoria. Llevá 6, pagá 5.",
  ],
  whisky: [
    "Destilados con procedencia. Elegidos uno por uno.",
    "Años de añejamiento en cada botella.",
  ],
  espirituosas: [
    "Botellas con carácter para mezclar o tomar solas.",
    "Con qué empezar a armar tu barra.",
  ],
  "vinos-guardados": [
    "Botellas que el tiempo hizo irrepetibles.",
    "Lo que quedó de esas añadas. Hasta 6 cuotas sin interés.",
  ],
  "wine-club": [
    "Cada mes, vinos que no encontrás. Cuatro membresías.",
    "Acceso a lo que aún no salió a la venta.",
  ],
  experiencias: [
    "Maridajes, fecha y lugar. Cupos limitados.",
  ],
  "gift-cards": [
    "La elección queda en sus manos.",
  ],
};
